---
- name: ensure web packages are the latest
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5
    - php-pear
    - php5-gd
    - php5-curl
    - php5-sqlite
    - php5-mysql
    - php5-pgsql
    - php5-memcache
    - mysql-client

- name: ensure apache modules are enabled
  apache2_module: name={{ item }}
  with_items:
    - rewrite
    - expires
    - auth_basic
    - headers
  register: a2module

- name: ensure apache site is configured
  template: >
    src=site.conf
    dest=/etc/apache2/sites-available/default
  register: siteconf

- name: ensure php is configured
  lineinfile: >
    dest=/etc/php5/apache2/php.ini
    regexp="max_execution_time = .*"
    line="max_execution_time = 120"
  register: phpconf

- name: ensure apache is restarted when needed
  service: name=apache2 state=restarted
  when: a2module.changed or siteconf.changed or phpconf.changed
